### PR TITLE
direct attention to redis compatibility

### PR DESCRIPTION
**Pull request by jonatron**
Just a little addition to the docs

### CODE REVIEW

**Comment by jonatron** [comment]
I quickly set up a new test project with Django 4, but I haven't quite replicated the same problem that I had in the project I'm working on. I'll figure it out soon so we know what to do here

**Comment by jonatron** [comment]
I wanted to understand what was happening, so I spent a while on this.
You can replicate the problem with `django_redis.cache.RedisCache` by creating a new project, and using `cache_page`+`WagtailCacheMixin` by having `mysite/home/models.py` like:
```
from django.utils.decorators import method_decorator
from wagtail.models import Page
from wagtailcache.cache import cache_page, WagtailCacheMixin

@method_decorator(cache_page, name="serve")
class HomePage(WagtailCacheMixin, Page):
    pass
```
settings like
```
 CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}
```

Switching to `"BACKEND": "wagtailcache.compat_backends.django_redis.RedisCache",` fixes the problem. As does `"BACKEND": "django.core.cache.backends.redis.RedisCache",` (to answer your question!)

There's another fix, by hacking `wagtailcache/cache.py` `UpdateCacheMiddleware` `process_response` , to use a function returning None rather than a lambda:
```
            if isinstance(response, SimpleTemplateResponse):
                def callback(r):
                    self._wagcache.set(cache_key, r, timeout)
                response.add_post_render_callback(
                    # lambda r: self._wagcache.set(cache_key, r, timeout)
                    callback
                )
```

**Comment by jonatron** [comment]
Updated the docs. The reason why returning None from the callback makes django_redis's backend work is here: [by using a function rather than lambda]
https://github.com/django/django/blob/main/django/template/response.py#L117
```
            for post_callback in self._post_render_callbacks:
                newretval = post_callback(retval)
                if newretval is not None:
                    retval = newretval
```

**Comment by vsalvino** [comment]
Go ahead and open a separate pull request with that callback change. As long as the tests pass, I think it would be good to merge it in. If that change will remove the need for our compat_backend, all the better, we can remove that as well.

**Pull request merged**
