### PR TITLE
Allow compatibility with Wagtail 4.0

### PR DESCRIPTION
**Pull request by cjkpl**
The current version 2.1.1 works well with Wagtail 4, except for configuration which disallows W4.
Suggested changes:

Bumped version to 2.1.2.
Changed requirements to Wagtail <=4.0

### CODE REVIEW

**Comment by aliceni81** [comment]
May I know if there will be a new release for wagtail 4 soon?

**Comment by cjkpl** [comment]
> May I know if there will be a new release for wagtail 4 soon?

You can temporarily use my fork with Wagtail 4.x:
https://github.com/cjkpl/wagtail-cache.git

Uninstall wagtail-cache, and then ```pip install git+https://github.com/cjkpl/wagtail-cache.git```

**Comment by aliceni81** [comment]
> > May I know if there will be a new release for wagtail 4 soon?
> 
> You can temporarily use my fork with Wagtail 4.x: https://github.com/cjkpl/wagtail-cache.git
> 
> Uninstall wagtail-cache, and then `pip install git+https://github.com/cjkpl/wagtail-cache.git`

Thank you so much!

**Comment by vsalvino** [comment]
@cjkpl can you please address the comments above? Specifically the wagtail<=5.0, which will re-trigger the unit tests to run so I can see the problems.

**Comment by cjkpl** [comment]
@vsalvino I can't see why the pytest fails on py>=3.8 - when I run pytest locally on 3.10 it passes without issues.

**Comment by vsalvino** [comment]
Here are the results of the pipeline: https://dev.azure.com/coderedcorp/cr-github/_build/results?buildId=3445&view=results

It looks like something in the cache middleware is broken due to the new version of Django (4.1) which Wagtail supports. You might want to try forcing your local dev environment to the latest version of everything:

```
pip install -e ./ --upgrade --upgrade-strategy eager
```

**Comment by mikaelclaesson** [comment]
Would it be possible to "fix" the problem by setting the requirements like this?

wagtail<5.0
Django<4.1

**Comment by cjkpl** [comment]
@mikaelclaesson As I cannot figure out how to fix it in django==4.1, this is exactly what I have just proposed, as a temporary solution.

**Comment by vsalvino** [comment]
There's no way we can ship it with a Django<4.1 constraint; we have to support whatever Wagtail supports.

I'm going to be travelling all next week for Djangocon, so might be able to look at this the week after.

**Comment by jonatron** [comment]
@vsalvino See https://github.com/coderedcorp/wagtail-cache/pull/50

**Comment by vsalvino** [comment]
Closing this in favor of #50

**Pull request closed without merging**
